INSERT INTO recipe (title, ingredients, instructions)
VALUES
    ('🍝 Pasta Carbonara', 'Pasta, Eggs, Cheese, Bacon', 'Cook pasta, mix with eggs and cheese, add bacon.'),
    ('🎃 Pumpkin Soup', 'Pumpkin, Carrots, Potatoes', 'Cook everything, add bouillon, mix it.'),
    ('🍫 Chocolate Cake', 'Flour, Sugar, Cocoa, Eggs', 'Mix ingredients, bake at 350F for 30 minutes.'),
    ('🥗 Caesar Salad', 'Romaine lettuce, Croutons, Parmesan cheese, Caesar dressing', 'Toss all ingredients together and serve.'),
    ('🍕 Margherita Pizza', 'Pizza dough, Tomato sauce, Fresh mozzarella, Basil', 'Spread sauce on dough, add cheese and basil, bake at 475F.'),
    ('🍣 Sushi Rolls', 'Sushi rice, Nori, Fish, Avocado, Soy sauce', 'Roll ingredients in nori, slice, and serve with soy sauce.'),
    ('🍛 Chicken Curry', 'Chicken, Curry powder, Coconut milk, Rice', 'Cook chicken with curry, add coconut milk, serve over rice.'),
    ('🥩 Grilled Steak', 'Steak, Olive oil, Salt, Pepper', 'Season steak and grill to desired doneness.'),
    ('🍦 Vanilla Ice Cream', 'Milk, Sugar, Vanilla extract, Cream', 'Mix ingredients and churn in an ice cream maker.'),
    ('🥔 Mashed Potatoes', 'Potatoes, Butter, Milk, Salt', 'Boil potatoes, mash with butter and milk, season to taste.'),
    ('🍗 Roast Chicken', 'Whole chicken, Olive oil, Herbs, Garlic', 'Rub chicken with oil and herbs, roast at 375F until cooked.'),
    ('🌮 Tacos', 'Taco shells, Ground beef, Lettuce, Tomato, Cheese', 'Cook beef, fill shells, and top with lettuce, tomato, and cheese.'),
    ('🍜 Ramen', 'Ramen noodles, Broth, Toppings (egg, green onions)', 'Cook noodles, add to hot broth, and top with desired ingredients.'),
    ('🥙 Falafel Wrap', 'Falafel, Pita bread, Lettuce, Tomato, Tahini sauce', 'Stuff pita with falafel and vegetables, drizzle with tahini.'),
    ('🍲 Beef Stew', 'Beef, Potatoes, Carrots, Onion, Broth', 'Brown beef, add vegetables and broth, simmer until tender.'),
    ('🍚 Fried Rice', 'Rice, Eggs, Peas, Carrots, Soy sauce', 'Stir-fry vegetables, add rice and eggs, season with soy sauce.'),
    ('🥒 Greek Salad', 'Cucumber, Tomato, Feta cheese, Olives, Olive oil', 'Mix all ingredients in a bowl and drizzle with olive oil.'),
    ('🍋 Lemon Bars', 'Flour, Sugar, Butter, Lemons, Eggs', 'Make crust, pour lemon filling, and bake until set.'),
    ('🍗 BBQ Ribs', 'Pork ribs, BBQ sauce, Spices', 'Rub ribs with spices, cook low and slow, baste with sauce.'),
    ('🍍 Pineapple Upside-Down Cake', 'Pineapple, Brown sugar, Butter, Cake mix', 'Layer pineapple and sugar, pour cake batter on top, bake.');
